"use strict";

import { TableDefinition } from "./types-ggs_backups";

export function backups(): TableDefinition {
  var definition: TableDefinition = {
    name: "backups",
    elementName: "backup",
    title: "Backups",
    tableName: "backups",
    editable:true,
    allow: {import:true},
    fields: [
        //campo propios:
        { name: "lote", typeName: "integer" },
        { name: "verificado", typeName: "text"},
        //campos fuentes externas:
        {name: "respid", typeName: "text", description: "Respondent ID", editable:false },
        {name: "intro", typeName: "text", description: "Intro", editable:false },
        {name: "int01", typeName: "text", description: "Interviewer ID", editable:false },
        {name: "int02", typeName: "text", description: "Interviewer's name", editable:false },
        {name: "demint", typeName: "text", description: "Demographics Intro", editable:false },
        {name: "dem01", typeName: "text", description: "Gender", editable:false },
        {name: "dem02", typeName: "text", description: "Date of birth", editable:false },
        {name: "dem03", typeName: "text", description: "Born in Country", editable:false },
        {name: "dem04a", typeName: "text", description: "Place of Birth", editable:false },
        {name: "dem04b", typeName: "text", description: "Country of Birth", editable:false },
        {name: "dem05", typeName: "text", description: "Date of immigration", editable:false },
        {name: "dem06", typeName: "text", description: "Activity Status", editable:false },
        {name: "dem07", typeName: "text", description: "Education Level", editable:false },
        {name: "dem08", typeName: "text", description: "Date education reached", editable:false },
        {name: "demacc", typeName: "text", description: "Accommodation Intro", editable:false },
        {name: "dem09", typeName: "text", description: "Number of Rooms", editable:false },
        {name: "dem10", typeName: "text", description: "Date moved in", editable:false },
        {name: "dem11", typeName: "text", description: "Housing Status", editable:false },
        {name: "dem12", typeName: "text", description: "Housing Satisfaction", editable:false },
        {name: "dem14", typeName: "text", description: "Internet connection", editable:false },
        {name: "dem15", typeName: "text", description: "Internet Use", editable:false },
        {name: "dem16", typeName: "text", description: "Language at home", editable:false },
        {name: "dem17", typeName: "text", description: "Living 3 years ago", editable:false },
        {name: "dem18", typeName: "text", description: "Reason for moving", editable:false },
        {name: "dem19", typeName: "text", description: "Intention to move", editable:false },
        {name: "dem20", typeName: "text", description: "Intention to migrate", editable:false },
        {name: "dem21", typeName: "text", description: "Respondent has a partner", editable:false },
        {name: "dem22a", typeName: "text", description: "Place first met current partner", editable:false },
        {name: "dem22", typeName: "text", description: "Partners date of birth", editable:false },
        {name: "dem23", typeName: "text", description: "Sex of Partner", editable:false },
        {name: "dem24a", typeName: "text", description: "Partner Born In Country", editable:false },
        {name: "dem24b", typeName: "text", description: "Partners country of birth", editable:false },
        {name: "dem24e", typeName: "text", description: "Partners date of immigration", editable:false },
        {name: "dem25", typeName: "text", description: "Partners education level [ISCED]", editable:false },
        {name: "dem26", typeName: "text", description: "Employment Status of Partner", editable:false },
        {name: "dem27", typeName: "text", description: "Everyday Activities Limitation of Partner", editable:false },
        {name: "dem28a", typeName: "text", description: "Married to Partner", editable:false },
        {name: "dem28b", typeName: "text", description: "Date married partner", editable:false },
        {name: "dem29a", typeName: "text", description: "Respondent has Registered Partnership", editable:false },
        {name: "dem29b", typeName: "text", description: "Date partnership registered", editable:false },
        {name: "dem30a", typeName: "text", description: "Living with Partner", editable:false },
        {name: "dem30b", typeName: "text", description: "Date started living with partner", editable:false },
        {name: "dem30c", typeName: "text", description: "Intention to start cohabiting", editable:false },
        {name: "dem30d", typeName: "text", description: "Intention to cohabit or marry", editable:false },
        {name: "dem28c", typeName: "text", description: "Intention to marry", editable:false },
        {name: "dem31", typeName: "text", description: "Date relationship started", editable:false },
        {name: "dem32a", typeName: "text", description: "Reason for living apart (most important one)", editable:false },
        {name: "dem32b", typeName: "text", description: "Respondent reason for living apart (most important one)", editable:false },
        {name: "dem32c", typeName: "text", description: "Partner reason for living apart (most important one)", editable:false },
        {name: "dem32d", typeName: "text", description: "Circumstances for living apart (most important one)", editable:false },
        {name: "dem33", typeName: "text", description: "Ever married to current partner", editable:false },
        {name: "dem33a", typeName: "text", description: "Date married current partner", editable:false },
        {name: "dem34", typeName: "text", description: "Date divorced current partner", editable:false },
        {name: "dem35", typeName: "text", description: "Residence of current partner [MIN]", editable:false },
        {name: "dem36a", typeName: "text", description: "Number of meetings with non-resident partner", editable:false },
        {name: "dem36au", typeName: "text", description: "Time unit of meetings with non-resident partner", editable:false },
        {name: "dem36b", typeName: "text", description: "Number of contacts with non-resident partner", editable:false },
        {name: "dem36bu", typeName: "text", description: "Time unit of contacts with non-resident partner", editable:false },
        {name: "dem37", typeName: "text", description: "Relationship Satisfaction", editable:false },
        {name: "dem38", typeName: "text", description: "Couple Disagreements: Intro", editable:false },
        {name: "dem38a", typeName: "text", description: "Couple Disagreements: Household Chores", editable:false },
        {name: "dem38b", typeName: "text", description: "Couple Disagreements: Money", editable:false },
        {name: "dem38c", typeName: "text", description: "Couple Disagreements: Leisure Time", editable:false },
        {name: "dem38d", typeName: "text", description: "Couple Disagreements: Relationship with friends", editable:false },
        {name: "dem38e", typeName: "text", description: "Couple Disagreements: Relationship with Parents and In Laws", editable:false },
        {name: "dem38f", typeName: "text", description: "Couple Disagreements: having children", editable:false },
        {name: "dem38g", typeName: "text", description: "Couple Disagreements: child raising issues", editable:false },
        {name: "dem39", typeName: "text", description: "Disagreement resolution: Intro", editable:false },
        {name: "dem39a", typeName: "text", description: "Disagreement resolution: giving in", editable:false },
        {name: "dem39b", typeName: "text", description: "Disagreement resolution: discuss calmly", editable:false },
        {name: "dem39c", typeName: "text", description: "Disagreement resolution: argue and shout", editable:false },
        {name: "dem39d", typeName: "text", description: "Disagreement resolution: refuse to talk", editable:false },
        {name: "dem40", typeName: "text", description: "Considered Break Up", editable:false },
        {name: "dem41", typeName: "text", description: "Respondent has children with partner", editable:false },
        {name: "dem42", typeName: "text", description: "Number of children with current partner [NUMBER]", editable:false },
        {name: "dem43", typeName: "text", description: "Respondent has adopted children with current partner", editable:false },
        {name: "dem44", typeName: "text", description: "Number of adopted children with current partner [NUMBER]", editable:false },
        {name: "dem45", typeName: "text", description: "Rs partner has children of her his own", editable:false },
        {name: "dem46", typeName: "text", description: "Number of children of Rs partner", editable:false },
        {name: "lhiint", typeName: "text", description: "Life History Intro", editable:false },
        {name: "lhi01", typeName: "text", description: "Lived with a partner before current one", editable:false },
        {name: "lhi02", typeName: "text", description: "Number of Partnerships [NUMBER]", editable:false },
        {name: "lhi03", typeName: "text", description: "Partner name", editable:false },
        {name: "lhi03_", typeName: "text", description: "Partner name", editable:false },
        {name: "lhi04a_", typeName: "text", description: "Place first met partner", editable:false },
        {name: "lhi04_", typeName: "text", description: "Date started cohabiting partner", editable:false },
        {name: "lhi05a_", typeName: "text", description: "Married to Partner", editable:false },
        {name: "lhi05b_", typeName: "text", description: "Date married partner", editable:false },
        {name: "lhi06_", typeName: "text", description: "Partner date of birth", editable:false },
        {name: "lhi07_", typeName: "text", description: "Children with Partner", editable:false },
        {name: "lhi08_", typeName: "text", description: "Number of Children with Partner", editable:false },
        {name: "lhi09_", typeName: "text", description: "Adopted children with Partner", editable:false },
        {name: "lhi10_", typeName: "text", description: "Number of children Adopted w/ Partner", editable:false },
        {name: "lhi11_", typeName: "text", description: "Step Children with Partner", editable:false },
        {name: "lhi12_", typeName: "text", description: "Step children with partner [NUMBER]", editable:false },
        {name: "lhi13_", typeName: "text", description: "How Partnership ended", editable:false },
        {name: "lhi14_", typeName: "text", description: "Date Partnership ended", editable:false },
        {name: "lhi15a_", typeName: "text", description: "Divorced Partner", editable:false },
        {name: "lhi15b_", typeName: "text", description: "Date divorce partner", editable:false },
        {name: "lhi16_", typeName: "text", description: "Who started divorce with Partner", editable:false },
        {name: "lhi17_", typeName: "text", description: "Partner was same sex", editable:false },
        {name: "lhi18", typeName: "text", description: "Had children outside of cohabitation", editable:false },
        {name: "lhi19", typeName: "text", description: "Number of Children outside of cohabitation", editable:false },
        {name: "lhi20", typeName: "text", description: "Child count verification", editable:false },
        {name: "lhi21", typeName: "text", description: "", editable:false },
        {name: "lhi22", typeName: "text", description: "Stepchildren [NUMBER]", editable:false },
        {name: "lhi23", typeName: "text", description: "Adopted children [NUMBER]", editable:false },
        {name: "lhi24", typeName: "text", description: "Child name", editable:false },
        {name: "lhi24_", typeName: "text", description: "Child name", editable:false },
        {name: "lhi25_", typeName: "text", description: "Child is alive", editable:false },
        {name: "lhi26_", typeName: "text", description: "Child Type", editable:false },
        {name: "lhi27_", typeName: "text", description: "Parent of Child", editable:false },
        {name: "lhi28_", typeName: "text", description: "Sex of child", editable:false },
        {name: "lhi29_", typeName: "text", description: "Child date of birth", editable:false },
        {name: "lhi30_", typeName: "text", description: "Child date of death", editable:false },
        {name: "lhi31_", typeName: "text", description: "Child living in same household as respondent", editable:false },
        {name: "lhi32_", typeName: "text", description: "Childs usual residency", editable:false },
        {name: "lhi33_", typeName: "text", description: "Looking after child [FREQ]", editable:false },
        {name: "lhi33u_", typeName: "text", description: "Frequency Looking after child [UNIT]", editable:false },
        {name: "lhi34_", typeName: "text", description: "Frequency of overnight stay", editable:false },
        {name: "lhi35_", typeName: "text", description: "Activity Status of child", editable:false },
        {name: "lhi36_", typeName: "text", description: "Limitation or disability of child", editable:false },
        {name: "lhi37_", typeName: "text", description: "Child health", editable:false },
        {name: "lhi38_", typeName: "text", description: "Child has ever lived in household", editable:false },
        {name: "lhi39a_", typeName: "text", description: "Freq meeting child", editable:false },
        {name: "lhi39au_", typeName: "text", description: "How often meeting child [UNIT]", editable:false },
        {name: "lhi39b_", typeName: "text", description: "Freq contact child", editable:false },
        {name: "lhi39bu_", typeName: "text", description: "How often contact child [UNIT]", editable:false },
        {name: "lhi40_", typeName: "text", description: "Child home [MIN]", editable:false },
        {name: "lhi41_", typeName: "text", description: "Relationship satisfaction with child", editable:false },
        {name: "ferint", typeName: "text", description: "Fertility Intro", editable:false },
        {name: "fer14", typeName: "text", description: "Intention to have a child in next 3 years", editable:false },
        {name: "fer15", typeName: "text", description: "Intention to have a child at all", editable:false },
        {name: "fer16a", typeName: "text", description: "Total number of children intended", editable:false },
        {name: "fer25", typeName: "text", description: "Child impact intro", editable:false },
        {name: "fer25a", typeName: "text", description: "Child Impact: the possibility to do what you want", editable:false },
        {name: "fer25b", typeName: "text", description: "Child Impact: the amount of money you can spend", editable:false },
        {name: "fer25c", typeName: "text", description: "Child Impact: the possibility to realize other goals in life", editable:false },
        {name: "fer25d", typeName: "text", description: "Child Impact: the joy and satisfaction you get from life", editable:false },
        {name: "fer25e", typeName: "text", description: "Child Impact: your employment opportunities", editable:false },
        {name: "fer25f", typeName: "text", description: "Child Impact: your partner's employment opportunities", editable:false },
        {name: "fer25g", typeName: "text", description: "Child Impact: security in old age", editable:false },
        {name: "fer25h", typeName: "text", description: "Child Impact: closeness with spouse", editable:false },
        {name: "fer26", typeName: "text", description: "Decision to have child Intro", editable:false },
        {name: "fer26a", typeName: "text", description: "Decision to have child: Financial", editable:false },
        {name: "fer26b", typeName: "text", description: "Decision to have child: Housing", editable:false },
        {name: "fer26c", typeName: "text", description: "Decision to have child: Health", editable:false },
        {name: "fer26d", typeName: "text", description: "Decision to have child: Feel Ready", editable:false },
        {name: "fer26e", typeName: "text", description: "Decision to have child: Suitable Partner", editable:false },
        {name: "fer26f", typeName: "text", description: "Decision to have child: Work Family balance", editable:false },
        {name: "fer26g", typeName: "text", description: "Decision to have child: Partners Health", editable:false },
        {name: "fer26h", typeName: "text", description: "Decision to have child: Childcare", editable:false },
        {name: "fer26i", typeName: "text", description: "Decision to have child: Leave", editable:false },
        {name: "fer27", typeName: "text", description: "Further Children Opinion Intro", editable:false },
        {name: "fer27a", typeName: "text", description: "Further Children Opinions: Friends", editable:false },
        {name: "fer27b", typeName: "text", description: "Further Children Opinions: Parents", editable:false },
        {name: "fer27c", typeName: "text", description: "Further Children Opinions: Partner", editable:false },
        {name: "fer16c", typeName: "text", description: "General ideal family size", editable:false },
        {name: "fer16b", typeName: "text", description: "Personal ideal family size", editable:false },
        {name: "fer17", typeName: "text", description: "Child Gender Preference", editable:false },
        {name: "fer02", typeName: "text", description: "Due date", editable:false },
        {name: "fer03", typeName: "text", description: "Pregnancy Intended", editable:false },
        {name: "fer04", typeName: "text", description: "Pregnancy Timing", editable:false },
        {name: "fer04b", typeName: "text", description: "Last Pregnancy Intended", editable:false },
        {name: "fer04c", typeName: "text", description: "Pregnancy Timing", editable:false },
        {name: "fer04d", typeName: "text", description: "Problems conceiving", editable:false },
        {name: "fer04e", typeName: "text", description: "Postpartum", editable:false },
        {name: "fer05", typeName: "text", description: "Able to have children", editable:false },
        {name: "fer06", typeName: "text", description: "Sterilized", editable:false },
        {name: "fer07_", typeName: "text", description: "Infertility Diagnosis", editable:false },
        {name: "fer08", typeName: "text", description: "Partner able to have children", editable:false },
        {name: "fer09", typeName: "text", description: "Partner Sterilized", editable:false },
        {name: "fer10a", typeName: "text", description: "Trying to get pregnant", editable:false },
        {name: "fer10b", typeName: "text", description: "Date started trying to get pregnant", editable:false },
        {name: "fer11_", typeName: "text", description: "Infertility Treatments", editable:false },
        {name: "fer12_", typeName: "text", description: "Contraception", editable:false },
        {name: "fer29", typeName: "text", description: "Contraception Autonomy", editable:false },
        {name: "fer13", typeName: "text", description: "Had intercourse in the last 4 weeks", editable:false },
        {name: "fer28", typeName: "text", description: "Sexual Autonomy", editable:false },
        {name: "fer21", typeName: "text", description: "Age of first menstruation", editable:false },
        {name: "fer24", typeName: "text", description: "Age starting menopause", editable:false },
        {name: "fer22", typeName: "text", description: "Age of voice breaking", editable:false },
        {name: "fer23", typeName: "text", description: "Age of first intercourse", editable:false },
        {name: "fer30", typeName: "text", description: "Miller Intro", editable:false },
        {name: "fer30a", typeName: "text", description: "JoysPBI", editable:false },
        {name: "fer30b", typeName: "text", description: "TradPar1", editable:false },
        {name: "fer30c", typeName: "text", description: "TradPar2", editable:false },
        {name: "fer30d", typeName: "text", description: "FeelNaC", editable:false },
        {name: "fer30e", typeName: "text", description: "InstVoC", editable:false },
        {name: "fer30f", typeName: "text", description: "SatChR", editable:false },
        {name: "fer30_2", typeName: "text", description: "Miller Addit", editable:false },
        {name: "fer30g", typeName: "text", description: "DiscPaC", editable:false },
        {name: "fer30h", typeName: "text", description: "FaWPar", editable:false },
        {name: "fer30i", typeName: "text", description: "NegChC1", editable:false },
        {name: "fer30j", typeName: "text", description: "NegChC2", editable:false },
        {name: "fer30k", typeName: "text", description: "NegChC3", editable:false },
        {name: "fer30l", typeName: "text", description: "ParStr", editable:false },
        {name: "hhdint", typeName: "text", description: "HH Grid Intro", editable:false },
        {name: "hhd01a", typeName: "text", description: "Other Household Members", editable:false },
        {name: "hhd01b", typeName: "text", description: "Number of Other Household Members", editable:false },
        {name: "hhd02", typeName: "text", description: "Name of HH Member", editable:false },
        {name: "hhd02_", typeName: "text", description: "Name of HH member", editable:false },
        {name: "hhd03_", typeName: "text", description: "Temporary Away HH Member", editable:false },
        {name: "hhd04_", typeName: "text", description: "HH Member Relationship to R", editable:false },
        {name: "hhd05_", typeName: "text", description: "Sex of HH Member", editable:false },
        {name: "hhd06_", typeName: "text", description: "HH member date of birth", editable:false },
        {name: "hhd07_", typeName: "text", description: "Activity of HH Member", editable:false },
        {name: "hhd08_", typeName: "text", description: "Relationship to R of HH Member", editable:false },
        {name: "hhd09_", typeName: "text", description: "Disability of HH Member", editable:false },
        {name: "hhd11", typeName: "text", description: "Household Tasks Intro", editable:false },
        {name: "hhd11a", typeName: "text", description: "Household Tasks: preparing meals", editable:false },
        {name: "hhd11b", typeName: "text", description: "Household Tasks: vacuuming", editable:false },
        {name: "hhd11c", typeName: "text", description: "Household Tasks: doing laundry", editable:false },
        {name: "hhd11d", typeName: "text", description: "Household Tasks: small repairs", editable:false },
        {name: "hhd11e", typeName: "text", description: "Household Tasks: finances", editable:false },
        {name: "hhd11f", typeName: "text", description: "Household Tasks: social", editable:false },
        {name: "hhd12", typeName: "text", description: "Household Tasks Satisfaction", editable:false },
        {name: "hhd13", typeName: "text", description: "Childcare Tasks Intro", editable:false },
        {name: "hhd13a", typeName: "text", description: "Childcare Tasks: dressing", editable:false },
        {name: "hhd13b", typeName: "text", description: "Childcare Tasks: stay with ill children", editable:false },
        {name: "hhd13c", typeName: "text", description: "Childcare Tasks: playing with children", editable:false },
        {name: "hhd13e", typeName: "text", description: "Childcare Tasks: putting children to bed", editable:false },
        {name: "hhd13d", typeName: "text", description: "Childcare Tasks: homework", editable:false },
        {name: "hhd14", typeName: "text", description: "Childcare Tasks Satisfaction", editable:false },
        {name: "hhd15", typeName: "text", description: "Decision Making Intro", editable:false },
        {name: "hhd15a", typeName: "text", description: "Decision Making: routine purchases", editable:false },
        {name: "hhd15b", typeName: "text", description: "Decision Making: expensive purchases", editable:false },
        {name: "hhd15c", typeName: "text", description: "Decision Making: time spent working", editable:false },
        {name: "hhd15d", typeName: "text", description: "Decision Making: time partner spends working", editable:false },
        {name: "hhd16", typeName: "text", description: "How income is organized", editable:false },
        {name: "hhd17", typeName: "text", description: "How expenses are organized", editable:false },
        {name: "hhd18", typeName: "text", description: "Regular help with childcare", editable:false },
        {name: "hhd19_", typeName: "text", description: "Regular help with childcare: People", editable:false },
        {name: "hhd20", typeName: "text", description: "Regular help with childcare: Frequency", editable:false },
        {name: "hhd20u", typeName: "text", description: "Regular help with childcare: Frequency [UNIT]", editable:false },
        {name: "hhd21", typeName: "text", description: "Regular help with childcare: Paid", editable:false },
        {name: "hhd22", typeName: "text", description: "Regular help with child care (institutional / from whom caring for children is a job)", editable:false },
        {name: "hhd23_", typeName: "text", description: "Childcare providers", editable:false },
        {name: "hhd24", typeName: "text", description: "Cost of Childcare", editable:false },
        {name: "hhd24u", typeName: "text", description: "Cost of Childcare [UNIT]", editable:false },
        {name: "hhd24a", typeName: "text", description: "Regularly pay for housework help", editable:false },
        {name: "hhd25", typeName: "text", description: "Helped others with childcare", editable:false },
        {name: "hhd26_", typeName: "text", description: "Helped others with childcare", editable:false },
        {name: "hhd28", typeName: "text", description: "Regular help with household tasks", editable:false },
        {name: "hhd29_", typeName: "text", description: "Regular help with household tasks", editable:false },
        {name: "hhd35", typeName: "text", description: "Given help with household tasks", editable:false },
        {name: "hhd36_", typeName: "text", description: "Given help with household tasks: People", editable:false },
        {name: "genint", typeName: "text", description: "Generations Intro", editable:false },
        {name: "gen01", typeName: "text", description: "Biological Mother still alive", editable:false },
        {name: "gen02", typeName: "text", description: "Biological Father still alive", editable:false },
        {name: "gen03", typeName: "text", description: "Parents live together", editable:false },
        {name: "gen09", typeName: "text", description: "Mothers date of birth", editable:false },
        {name: "gen10", typeName: "text", description: "Mothers date of death", editable:false },
        {name: "gen11", typeName: "text", description: "Is mother born in the country", editable:false },
        {name: "gen12", typeName: "text", description: "Mothers country of birth", editable:false },
        {name: "gen15a", typeName: "text", description: "Freq of meeting with Mother", editable:false },
        {name: "gen15au", typeName: "text", description: "Freq of meeting with Mother [UNIT]", editable:false },
        {name: "gen15b", typeName: "text", description: "Freq of contact with Mother", editable:false },
        {name: "gen15bu", typeName: "text", description: "Freq of contact with Mother [UNIT]", editable:false },
        {name: "gen16", typeName: "text", description: "Satisfaction with the relationship with Mother", editable:false },
        {name: "gen23", typeName: "text", description: "Fathers date of birth", editable:false },
        {name: "gen24", typeName: "text", description: "Fathers date of death", editable:false },
        {name: "gen25", typeName: "text", description: "Is father born in [COUNTRY]", editable:false },
        {name: "gen26", typeName: "text", description: "Fathers country of birth", editable:false },
        {name: "gen29a", typeName: "text", description: "Freq of meeting with Father", editable:false },
        {name: "gen29au", typeName: "text", description: "Time Unit Freq of Meeting wih Father [UNIT]", editable:false },
        {name: "gen29b", typeName: "text", description: "Freq of contact with Father", editable:false },
        {name: "gen29bu", typeName: "text", description: "Time Unit Freq of contact wih Father [UNIT]", editable:false },
        {name: "gen30", typeName: "text", description: "Satisfaction with the relationship with Father", editable:false },
        {name: "gen37a", typeName: "text", description: "Biological parents married", editable:false },
        {name: "gen37", typeName: "text", description: "Date of parents marriage", editable:false },
        {name: "gen38a", typeName: "text", description: "Biological parents Broke Up", editable:false },
        {name: "gen38b", typeName: "text", description: "Date of parents break up", editable:false },
        {name: "gen39a", typeName: "text", description: "Number of Brothers", editable:false },
        {name: "gen39b", typeName: "text", description: "Number of Sisters", editable:false },
        {name: "gen40", typeName: "text", description: "Birth order of siblings", editable:false },
        {name: "gen41a", typeName: "text", description: "Year mother's first birth", editable:false },
        {name: "gen41b", typeName: "text", description: "Year father's first birth", editable:false },
        {name: "gen42", typeName: "text", description: "Lived as a child", editable:false },
        {name: "gen43", typeName: "text", description: "Region where living during childhood until age 15", editable:false },
        {name: "gen44a", typeName: "text", description: "Country of residence in childhood", editable:false },
        {name: "gen44b", typeName: "text", description: "Lived abroad for more than a year", editable:false },
        {name: "gen45", typeName: "text", description: "With both biological parents during childhood until age 15", editable:false },
        {name: "gen46", typeName: "text", description: "With whom R lived until age 15", editable:false },
        {name: "genint2", typeName: "text", description: "Generations Intro2", editable:false },
        {name: "gen47", typeName: "text", description: "Parents relationship in Rs childhood", editable:false },
        {name: "gen48", typeName: "text", description: "Fathers Occupation when R was age 15 (see code ISCO)", editable:false },
        {name: "gen49", typeName: "text", description: "Fathers highest education level (see code ISCED)", editable:false },
        {name: "gen50", typeName: "text", description: "Mothers Occupation when R was age 15 (see code ISCO)", editable:false },
        {name: "gen51", typeName: "text", description: "Mothers highest education level (see code ISCED)", editable:false },
        {name: "gen52", typeName: "text", description: "Ever lived separately from parents", editable:false },
        {name: "gen52a", typeName: "text", description: "Date moved out from parents", editable:false },
        {name: "gen53", typeName: "text", description: "Intention to start living separately from parents", editable:false },
        {name: "gen54", typeName: "text", description: "Number of Grandparents Alive", editable:false },
        {name: "gen55", typeName: "text", description: "Has grandchild", editable:false },
        {name: "gen56", typeName: "text", description: "Number of Grandchildren", editable:false },
        {name: "gen57", typeName: "text", description: "Grandchilds date of birth", editable:false },
        {name: "gen58", typeName: "text", description: "Any regular help needed in personal care", editable:false },
        {name: "gen59", typeName: "text", description: "Persons in HH who helped with care", editable:false },
        {name: "gen60_", typeName: "text", description: "Received other help with care: People", editable:false },
        {name: "gen63", typeName: "text", description: "Regular professional help with personal care (institutional/ from professional person)", editable:false },
        {name: "gen66", typeName: "text", description: "Given personal care", editable:false },
        {name: "gen67_", typeName: "text", description: "Given personal care", editable:false },
        {name: "gen68", typeName: "text", description: "Any financial transfer from persons inside or outside HH", editable:false },
        {name: "gen69_", typeName: "text", description: "Received Financial Transfer: People", editable:false },
        {name: "gen70", typeName: "text", description: "Any financial transfer to persons inside or outside HH", editable:false },
        {name: "gen71_", typeName: "text", description: "Given Financial Transfer: People", editable:false },
        {name: "welint", typeName: "text", description: "Wellbeing Intro", editable:false },
        {name: "wel01", typeName: "text", description: "Life Satisfaction", editable:false },
        {name: "wel02", typeName: "text", description: "Subjective Health", editable:false },
        {name: "wel02a", typeName: "text", description: "Healthcare Autonomy", editable:false },
        {name: "wel03_", typeName: "text", description: "Health Conditions", editable:false },
        {name: "wel04", typeName: "text", description: "Everyday Activity Limitation", editable:false },
        {name: "wel05", typeName: "text", description: "Since when limited in ability to carry out activities", editable:false },
        {name: "wel06", typeName: "text", description: "Weight (kg)", editable:false },
        {name: "wel07", typeName: "text", description: "Height (cm)", editable:false },
        {name: "wel08", typeName: "text", description: "Happiness Scale", editable:false },
        {name: "wel09", typeName: "text", description: "Loneliness: Intro", editable:false },
        {name: "wel09a", typeName: "text", description: "Loneliness: People to lean on", editable:false },
        {name: "wel09b", typeName: "text", description: "Loneliness: General sense of emptiness", editable:false },
        {name: "wel09c", typeName: "text", description: "Loneliness: Miss having people around", editable:false },
        {name: "wel09d", typeName: "text", description: "Loneliness: Many people I can trust", editable:false },
        {name: "wel09e", typeName: "text", description: "Loneliness: Feel rejected", editable:false },
        {name: "wel09f", typeName: "text", description: "Loneliness: Enough people I feel close to", editable:false },
        {name: "wel10_", typeName: "text", description: "Discuss Important Matters", editable:false },
        {name: "wel11", typeName: "text", description: "Depression: Intro", editable:false },
        {name: "wel11a", typeName: "text", description: "Depression: Couldn't shake off the blues", editable:false },
        {name: "wel11b", typeName: "text", description: "Depression: Felt Depressed", editable:false },
        {name: "wel11c", typeName: "text", description: "Depression: Felt life was a failure", editable:false },
        {name: "wel11d", typeName: "text", description: "Depression: Felt fearful", editable:false },
        {name: "wel11e", typeName: "text", description: "Depression: Felt sad", editable:false },
        {name: "wrkint", typeName: "text", description: "Work Intro", editable:false },
        {name: "wrk01", typeName: "text", description: "Satisfaction with Employment Status", editable:false },
        {name: "wrk03", typeName: "text", description: "Date of starting status", editable:false },
        {name: "wrk02", typeName: "text", description: "Employment Status", editable:false },
        {name: "wrk04_3601", typeName: "text", description: "Occupation 1", editable:false },
        {name: "wrk04_3602", typeName: "text", description: "Occupation 2", editable:false },
        {name: "wrk06", typeName: "text", description: "Full time or Part Time", editable:false },
        {name: "wrk07", typeName: "text", description: "Hours worked per week", editable:false },
        {name: "wrk08", typeName: "text", description: "Commute time [MIN]", editable:false },
        {name: "wrk09", typeName: "text", description: "Fixed start and finish times", editable:false },
        {name: "wrk10", typeName: "text", description: "Work from home", editable:false },
        {name: "wrk11", typeName: "text", description: "Works in the evening", editable:false },
        {name: "wrk12", typeName: "text", description: "Evening work location", editable:false },
        {name: "wrk13", typeName: "text", description: "Works weekends", editable:false },
        {name: "wrk14", typeName: "text", description: "Weekend work location", editable:false },
        {name: "wrk15", typeName: "text", description: "Work Balance: Intro", editable:false },
        {name: "wrk15a", typeName: "text", description: "Work balance: too tired to do chores", editable:false },
        {name: "wrk15b", typeName: "text", description: "Work balance: difficult to fulfil family responsibilities", editable:false },
        {name: "wrk15c", typeName: "text", description: "Work balance: too tired function at work", editable:false },
        {name: "wrk15d", typeName: "text", description: "Work balance: hard to concentrate because of family responsibilities", editable:false },
        {name: "wrk16a", typeName: "text", description: "Might lose job in next 12 months", editable:false },
        {name: "wrk16b", typeName: "text", description: "Intention to give up work", editable:false },
        {name: "wrk17", typeName: "text", description: "Organization Type", editable:false },
        {name: "wrk18", typeName: "text", description: "Current contract type", editable:false },
        {name: "wrk20", typeName: "text", description: "Flexible work arrangements", editable:false },
        {name: "wrk21", typeName: "text", description: "Additional job or business", editable:false },
        {name: "wrk22", typeName: "text", description: "Hours worked per week in additional job or business", editable:false },
        {name: "wrk23", typeName: "text", description: "Number of employees", editable:false },
        {name: "wrk24", typeName: "text", description: "Opportunity to resume work after leave", editable:false },
        {name: "wrk25", typeName: "text", description: "Intention to work after leave", editable:false },
        {name: "wrk26", typeName: "text", description: "Job before current activity", editable:false },
        {name: "wrk27_3601", typeName: "text", description: "Last Occupation 1", editable:false },
        {name: "wrk27_3602", typeName: "text", description: "Last Occupation 2", editable:false },
        {name: "wrk28", typeName: "text", description: "Previous employment status", editable:false },
        {name: "wrk30", typeName: "text", description: "Reason for stopping work", editable:false },
        {name: "wrk30a", typeName: "text", description: "Date of stopping work", editable:false },
        {name: "wrk31", typeName: "text", description: "Intention to take job or start a business", editable:false },
        {name: "wrk32", typeName: "text", description: "Activity Status", editable:false },
        {name: "wrk34_3601", typeName: "text", description: "Partners Occupation 1", editable:false },
        {name: "wrk34_3602", typeName: "text", description: "Partners Occupation 2", editable:false },
        {name: "wrk35", typeName: "text", description: "Partners hours worked per week", editable:false },
        {name: "wrk36", typeName: "text", description: "Partners fixed start and finish times", editable:false },
        {name: "wrk37", typeName: "text", description: "Partner works from home", editable:false },
        {name: "wrk38", typeName: "text", description: "Partner works in the evening", editable:false },
        {name: "wrk39", typeName: "text", description: "Partners evening work location", editable:false },
        {name: "wrk40", typeName: "text", description: "Partners works weekends", editable:false },
        {name: "wrk41", typeName: "text", description: "Partners weekend work location", editable:false },
        {name: "wrk42", typeName: "text", description: "Might lose job in next 12 months", editable:false },
        {name: "wrk43", typeName: "text", description: "Partners Organization Type", editable:false },
        {name: "wrk44", typeName: "text", description: "Current contract type", editable:false },
        {name: "wrk46", typeName: "text", description: "Partner has flexible work arrangements", editable:false },
        {name: "wrk47", typeName: "text", description: "Partners additional job or business", editable:false },
        {name: "wrk48", typeName: "text", description: "Partners hours worked per week in additional job or business", editable:false },
        {name: "wrk49", typeName: "text", description: "Number of employees", editable:false },
        {name: "wrk50", typeName: "text", description: "Partners reason for stopping work", editable:false },
        {name: "incint", typeName: "text", description: "Income Intro", editable:false },
        {name: "inc01", typeName: "text", description: "Value of Property (House and Land)", editable:false },
        {name: "inc03", typeName: "text", description: "Can make ends meet", editable:false },
        {name: "inc13", typeName: "text", description: "Ever received large financial transfer", editable:false },
        {name: "inc14_", typeName: "text", description: "Received large financial transfer: People", editable:false },
        {name: "inc15", typeName: "text", description: "Received large financial transfer [YEAR]", editable:false },
        {name: "inc04", typeName: "text", description: "HH can afford: Intro", editable:false },
        {name: "inc04a", typeName: "text", description: "HH can afford: keep house warm", editable:false },
        {name: "inc04b", typeName: "text", description: "HH can afford: weeks holiday", editable:false },
        {name: "inc04c", typeName: "text", description: "HH can afford: replacing furniture", editable:false },
        {name: "inc04d", typeName: "text", description: "HH can afford: new clothes", editable:false },
        {name: "inc04e", typeName: "text", description: "HH can afford: eating meat", editable:false },
        {name: "inc04f", typeName: "text", description: "HH can afford: entertaining friends and family", editable:false },
        {name: "inc04g", typeName: "text", description: "HH can afford: unexpected expenses", editable:false },
        {name: "inc04h", typeName: "text", description: "HH can afford: access to a car", editable:false },
        {name: "inc04i", typeName: "text", description: "HH can afford: two pairs of shoes", editable:false },
        {name: "inc04j", typeName: "text", description: "HH can afford: pocket money", editable:false },
        {name: "inc04k", typeName: "text", description: "HH can afford: leisure activities", editable:false },
        {name: "inc05", typeName: "text", description: "HH couldnt pay: Intro", editable:false },
        {name: "inc08_", typeName: "text", description: "Type of Income", editable:false },
        {name: "inc06", typeName: "text", description: "Total Household Net Income", editable:false },
        {name: "inc12", typeName: "text", description: "Income in 3 years", editable:false },
        {name: "attint", typeName: "text", description: "Attitudes Intro", editable:false },
        {name: "att01", typeName: "text", description: "General Trust", editable:false },
        {name: "att02", typeName: "text", description: "Planning Scale", editable:false },
        {name: "att03", typeName: "text", description: "Values: Intro", editable:false },
        {name: "att03a", typeName: "text", description: "Values: Marriage Outdated", editable:false },
        {name: "att03b", typeName: "text", description: "Values: Unmarried Cohabitation", editable:false },
        {name: "att03d", typeName: "text", description: "Values: Divorce is permissible", editable:false },
        {name: "att03e", typeName: "text", description: "Values: Women need children to be fulfilled", editable:false },
        {name: "att03g", typeName: "text", description: "Values: Child needs a father and mother", editable:false },
        {name: "att03h", typeName: "text", description: "Values: Men need children to be fulfilled", editable:false },
        {name: "att03i", typeName: "text", description: "Values: Homosexual couple rights", editable:false },
        {name: "att03j", typeName: "text", description: "Values: Pre-school child suffers if mother works", editable:false },
        {name: "att05", typeName: "text", description: "Intergenerational Values: Intro", editable:false },
        {name: "att05b", typeName: "text", description: "Intergenerational Values: Parents provide financial help", editable:false },
        {name: "att06a", typeName: "text", description: "Intergenerational Care Values: Children should care for parents", editable:false },
        {name: "att06b", typeName: "text", description: "Intergenerational Care Values: Children should provide financial help for parents", editable:false },
        {name: "att07", typeName: "text", description: "Gender Values: Intro", editable:false },
        {name: "att07a", typeName: "text", description: "Gender Values: Better Political Leaders", editable:false },
        {name: "att07b", typeName: "text", description: "Gender Values: For whom is university most important", editable:false },
        {name: "att07c", typeName: "text", description: "Gender Values: For whom is having a job more important", editable:false },
        {name: "att07d", typeName: "text", description: "Gender Values: For whom is looking after children more important", editable:false },
        {name: "att07g", typeName: "text", description: "Gender Values: Better at caring for children", editable:false },
        {name: "att11b", typeName: "text", description: "Ideal work hours for mothers", editable:false },
        {name: "att11d", typeName: "text", description: "Ideal work hours for fathers", editable:false },
        {name: "att08", typeName: "text", description: "Religious Denomination", editable:false },
        {name: "att09", typeName: "text", description: "Religious service [FREQ]", editable:false },
        {name: "att09u", typeName: "text", description: "Religious service [UNIT]", editable:false },
        {name: "att10", typeName: "text", description: "Religiosity", editable:false },
        {name: "rep01", typeName: "text", description: "Others present at interview", editable:false },
        {name: "rep02", typeName: "text", description: "Respondent influenced", editable:false },
        {name: "rep03", typeName: "text", description: "In what way was R influenced", editable:false },
        {name: "rep04", typeName: "text", description: "Questions where influenced", editable:false },
        {name: "rep05", typeName: "text", description: "Willingness to answer questions", editable:false },
        {name: "rep06", typeName: "text", description: "Quality of information", editable:false },
        {name: "rep07", typeName: "text", editable:false },
        {name: "thanks", typeName: "text", editable:false },
        {name: "dem04biso", typeName: "text", description: "Country of Birth (ISO CODE)", editable:false },
        {name: "dem24biso", typeName: "text", description: "Country of Birth of Partner (ISO CODE)", editable:false },
        {name: "dem24c", typeName: "text", description: "Citizenship of Partner", editable:false },
        {name: "pdob_date", typeName: "text", editable:false },
        {name: "lhi29_fulldate", typeName: "text", editable:false },
        {name: "childage_", typeName: "text", editable:false },
        {name: "youngchildname", typeName: "text", editable:false },
        {name: "fer01a", typeName: "text", description: "Respondent Pregnant", editable:false },
        {name: "fer01b", typeName: "text", description: "Partner Pregnant", editable:false },
        {name: "fer01c", typeName: "text", description: "Non-partner Pregnant", editable:false },
        {name: "hhd23a", typeName: "text", description: "Childcare Frequency: Babysitter", editable:false },
        {name: "hhd23b", typeName: "text", description: "Childcare Frequency: Day Care Centre", editable:false },
        {name: "hhd23c", typeName: "text", description: "Childcare Frequency: Nursery or Pre school", editable:false },
        {name: "hhd23d", typeName: "text", description: "Childcare Frequency: After school care centre", editable:false },
        {name: "hhd23e", typeName: "text", description: "Childcare Frequency: Self organised childcare group", editable:false },
        {name: "hhd23f", typeName: "text", description: "Childcare Frequency: Other", editable:false },
        {name: "hhd23au", typeName: "text", description: "Childcare Frequency [UNIT]: Babysitter", editable:false },
        {name: "hhd23bu", typeName: "text", description: "Childcare Frequency [UNIT]: Day Care Centre", editable:false },
        {name: "hhd23cu", typeName: "text", description: "Childcare Frequency [UNIT]: Nursery or Pre-school", editable:false },
        {name: "hhd23du", typeName: "text", description: "Childcare Frequency [UNIT]: After school care centre", editable:false },
        {name: "hhd23eu", typeName: "text", description: "Childcare Frequency [UNIT]: Self-organised childcare group", editable:false },
        {name: "hhd23fu", typeName: "text", description: "Childcare Frequency [UNIT]: Other", editable:false },
        {name: "hhd30", typeName: "text", description: "Regular help with household tasks: Frequency", editable:false },
        {name: "hhd30u", typeName: "text", description: "Regular help with household tasks: Frequency [UNIT]", editable:false },
        {name: "hhd31", typeName: "text", description: "Regular help with household tasks: Paid", editable:false },
        {name: "hhd37", typeName: "text", description: "Received maintenance payments for children", editable:false },
        {name: "hhd38", typeName: "text", description: "Given maintenance payments for children", editable:false },
        {name: "hhd39", typeName: "text", description: "Recieved Alimony from former partner", editable:false },
        {name: "hhd40", typeName: "text", description: "Given Alimony to former partner", editable:false },
        {name: "gen12iso", typeName: "text", description: "Mothers country of birth (ISO CODE)", editable:false },
        {name: "gen26iso", typeName: "text", description: "Fathers Country of Birth (ISO CODE)", editable:false },
        {name: "gen41a_3601", typeName: "text", description: "[AR] Year mother's first birth - ranges", editable:false },
        {name: "gen41b_3601", typeName: "text", description: "[AR] Year father's first birth - ranges", editable:false },
        {name: "gen44aiso", typeName: "text", description: "Country where living during childhood until age 15 (ISO CODE)", editable:false },
        {name: "gen48isco", typeName: "text", description: "Fathers Occupation when R was age 15 (see code ISCO)", editable:false },
        {name: "gen50isco", typeName: "text", description: "Mothers Occupation when R was age 15 (see code ISCO)", editable:false },
        {name: "acountry", typeName: "text", editable:false },
        {name: "intst", typeName: "text", editable:false },
        {name: "intdate", typeName: "text", editable:false },
        {name: "dobm", typeName: "text", editable:false },
        {name: "doby", typeName: "text", editable:false },
        {name: "dobdate", typeName: "text", editable:false },
        {name: "p_dobm", typeName: "text", editable:false },
        {name: "p_doby", typeName: "text", editable:false },
        {name: "intdatem", typeName: "text", description: "Month of Interview", editable:false },
        {name: "intdatey", typeName: "text", description: "Year of Interview", editable:false },
        {name: "asex", typeName: "text", editable:false },
        {name: "age", typeName: "text", editable:false },
        {name: "partnerage", typeName: "text", editable:false },
        {name: "mumcores", typeName: "text", editable:false },
        {name: "dadcores", typeName: "text", editable:false },
        {name: "parentalive", typeName: "text", editable:false },
        {name: "haspartner", typeName: "text", editable:false },
        {name: "corespartner", typeName: "text", editable:false },
        {name: "coreskids", typeName: "text", editable:false },
        {name: "haschild", typeName: "text", editable:false },
        {name: "childover6", typeName: "text", description: "Child over 6", editable:false },
        {name: "hhsize", typeName: "text", editable:false },
        {name: "hasyoungchild", typeName: "text", description: "Child under 6", editable:false },
        {name: "hasbiolchildunder15", typeName: "text", description: "Biological child under 15", editable:false },
        {name: "homeowner", typeName: "text", editable:false },
        {name: "hasmortgage", typeName: "text", editable:false },
        {name: "mode", typeName: "text", editable:false },
        {name: "numpartners", typeName: "text", editable:false },
        {name: "numbiol", typeName: "text", editable:false },
        {name: "numstep", typeName: "text", editable:false },
        {name: "numadopt", typeName: "text", editable:false },
        {name: "totalchildren", typeName: "text", editable:false },
        {name: "childrenpartner_", typeName: "text", editable:false },
        {name: "bdemographics", typeName: "text", editable:false },
        {name: "blifehist", typeName: "text", editable:false },
        {name: "bhousehold", typeName: "text", editable:false },
        {name: "bgenerations", typeName: "text", editable:false },
        {name: "bfertility", typeName: "text", editable:false },
        {name: "bwellbeing", typeName: "text", editable:false },
        {name: "bwork", typeName: "text", editable:false },
        {name: "bincome", typeName: "text", editable:false },
        {name: "battitudes", typeName: "text", editable:false },
        {name: "breport", typeName: "text", editable:false },
        {name: "begindate", typeName: "text", editable:false },
        {name: "begintime", typeName: "text", editable:false },
        {name: "enddate", typeName: "text", editable:false },
        {name: "endtime", typeName: "text", editable:false },
    ],
    primaryKey: ["lote", "respid"],
    foreignKeys: [{ references: "lotes", fields: ["lote"] }],
    // hiddenColumns: [
    //    "modificado",
    // ],
  };
  return definition;
}
